### ISSUE TITLE
java.lang.BootstrapMethodError: Exception from call site #11 bootstrap method

### ISSUE THREAD

**Issue by yoldar** [helpcrunch/android-sdk-demo#10]
Hi! I'm getting this error:

2020-02-21 11:14:03.231 23606-23606/kz.metaphora.mkkm2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kz.metaphora.mkkm2, PID: 23606
    java.lang.BootstrapMethodError: Exception from call site #11 bootstrap method
        at com.socket_n.client.Manager.socket(Manager.java:397)
        at com.socket_n.client.IO.socket(IO.java:97)
        at com.socket_n.client.IO.socket(IO.java:44)
        at com.helpcrunch.library.core.repository.socket.ActiveSocketStore.initOnlinerSocket(ActiveSocketStore.kt:54)
        at com.helpcrunch.library.core.repository.Repository.initOnlinerSocket(Repository.kt:78)
        at com.helpcrunch.library.core.HelpCrunchPresenter.init(HelpCrunchPresenter.kt:69)
        at com.helpcrunch.library.core.HelpCrunch.initialize(HelpCrunch.kt:108)
        at com.helpcrunch.library.core.HelpCrunch.initialize$default(HelpCrunch.kt:104)
        at com.helpcrunch.library.core.HelpCrunch.initialize(Unknown Source:10)
        at kz.metaphora.mkkm2.BaseApplication.init(BaseApplication.java:36)
        at kz.metaphora.mkkm2.BaseApplication.onCreate(BaseApplication.java:31)
        at kz.metaphora.mkkm2.BA.onCreate(BA.java:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.socket_n.client.Manager.socket(Manager.java:397) 
        at com.socket_n.client.IO.socket(IO.java:97) 
        at com.socket_n.client.IO.socket(IO.java:44) 
        at com.helpcrunch.library.core.repository.socket.ActiveSocketStore.initOnlinerSocket(ActiveSocketStore.kt:54) 
        at com.helpcrunch.library.core.repository.Repository.initOnlinerSocket(Repository.kt:78) 
        at com.helpcrunch.library.core.HelpCrunchPresenter.init(HelpCrunchPresenter.kt:69) 
        at com.helpcrunch.library.core.HelpCrunch.initialize(HelpCrunch.kt:108) 
        at com.helpcrunch.library.core.HelpCrunch.initialize$default(HelpCrunch.kt:104) 
        at com.helpcrunch.library.core.HelpCrunch.initialize(Unknown Source:10) 
        at kz.metaphora.mkkm2.BaseApplication.init(BaseApplication.java:36) 
        at kz.metaphora.mkkm2.BaseApplication.onCreate(BaseApplication.java:31) 
        at kz.metaphora.mkkm2.BA.onCreate(BA.java:9) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

build.gradle:
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "kz.metaphora.mkkm2"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 62
        versionName "2.0.62"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation 'com.jakewharton:butterknife:8.0.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.0.1'

    implementation 'com.google.code.gson:gson:2.2.4'

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.legacy:legacy-preference-v14:1.0.0'

    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    implementation 'net.objecthunter:exp4j:0.4.4'
    implementation 'com.google.protobuf:protobuf-java:3.5.+'
    implementation 'com.github.TheKhaeng:PinLockView:master-SNAPSHOT'

    implementation group: 'com.google.zxing', name: 'core', version: '3.2.1'
    implementation group: 'com.google.zxing', name: 'android-core', version: '3.2.0'

    implementation 'com.google.firebase:firebase-core:17.2.2'
    implementation 'com.google.firebase:firebase-messaging:20.1.0'
    implementation('com.google.firebase:firebase-config:19.1.0') {
        exclude group: 'com.google.protobuf', module: 'protobuf-lite'
    }
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
    implementation 'com.borax12.materialdaterangepicker:library:1.9'

    implementation 'com.jakewharton.threetenabp:threetenabp:1.2.1'

    implementation 'com.android.support:multidex:1.0.1'

    implementation 'com.helpcrunch:sdk:2.0.0-rc.5'
}

apply plugin: 'com.google.gms.google-services'

**Comment by TalbotGooday** [comment]
Hi. Thanks for your report. Just add this to your `build.gradle (app)` file:
```groovy
android {
       //....
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }
```

**Comment by yoldar** [comment]
@TalbotGooday Thanks!
