### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#21]
Hi, I got this `ConcurrentModificationException` from two of my users.
Both of them are running Android 10, and the app was running in the foreground.

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
       at com.helpcrunch.library.d.c.a$w.call(a.java:442)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at a.a.b.e.b(e.java:336)
       at a.a.b.e.c(e.java:284)
       at a.a.b.e.a(e.java:28)
       at a.a.b.e$b$b.call(e.java:123)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at a.a.b.c.b(c.java:372)
       at a.a.b.c.lambda$EpPtBzBqeced58fz7epZ1AHEq80(c.java:2)
       at a.a.b.-$$Lambda$c$EpPtBzBqeced58fz7epZ1AHEq80.a(-.java:2)
       at a.a.d.b$b.a(b.java:178)
       at a.a.b.c.c(c.java:364)
       at a.a.b.c.a(c.java:31)
       at a.a.b.c$e.call(c.java:340)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
       at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
       at io.socket.engineio.client.Socket$5.call(Socket.java:335)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
       at io.socket.engineio.client.Transport.onData(Transport.java:118)
       at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
       at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
       at io.socket.thread.EventThread$2.run(EventThread.java:80)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
       
Unfortunately, I can't deal with it because of obfuscation!

**Comment by TalbotGooday** [comment]
Thanks for the report!

**Comment by malik082009** [comment]
I also got this exception:
```
Fatal Exception: java.util.ConcurrentModificationException at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757) at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780) at io.socket.hasbinary.HasBinary._hasBinary(HasBinary.java:47) at io.socket.hasbinary.HasBinary._hasBinary(HasBinary.java:39) at io.socket.hasbinary.HasBinary.hasBinary(HasBinary.java:18) at io.socket.parser.IOParser$Encoder.encode(IOParser.java:27) at io.socket.client.Manager.packet(Manager.java:412) at io.socket.client.Socket.packet(Socket.java:230) at io.socket.client.Socket.access$1000(Socket.java:18) at io.socket.client.Socket$6.run(Socket.java:219) at io.socket.thread.EventThread.exec(EventThread.java:55) at io.socket.client.Socket.emit(Socket.java:198) at io.socket.client.Socket$5.run(Socket.java:183) at io.socket.thread.EventThread$2.run(EventThread.java:80) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:923)

implementation('io.socket:socket.io-client:2.0.1') { exclude group: 'org.json', module: 'json' }
```

**Comment by TalbotGooday** [comment]
@malik082009 thanks for the report. As I see it's socket.io exception. Unfortunately, we cannot fix this. But you can leave a report here: https://github.com/socketio/socket.io-client-java
