### ISSUE TITLE
NPE: com.helpcrunch.library.utils.views.indicator.AVLoadingIndicatorView.setIndicatorColor(int)

### ISSUE THREAD

**Issue by nostra13** [helpcrunch/android-sdk-demo#24]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.helpcrunch.library.utils.views.indicator.AVLoadingIndicatorView.setIndicatorColor(int)' on a null object reference
       at com.helpcrunch.library.e.b.b.f.f.d.<init>(d.java:10)
       at com.helpcrunch.library.e.b.b.f.b.a(b.java:92)
       at com.helpcrunch.library.e.b.b.f.c.onCreateViewHolder(c.java:41)
       at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
       at android.view.View.layout(View.java:20684)
       at android.view.ViewGroup.layout(ViewGroup.java:6194)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2804)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2331)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1471)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7211)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
       at android.view.Choreographer.doCallbacks(Choreographer.java:816)
       at android.view.Choreographer.doFrame(Choreographer.java:751)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

`implementation "com.helpcrunch:chat-sdk:3.0.7"`
**Android:** 9
**Device:** ZenFone Max Pro M2 (ZB631KL) (WW) / Max Pro M2 (ZB630KL) (IN)

**Comment by TalbotGooday** [comment]
Thanks for the report! Will be fixed in the next release!
