### ISSUE TITLE
Can only download HTTP/HTTPS URIs

### ISSUE THREAD

**Issue by nostra13** [helpcrunch/android-sdk-demo#25]
Crash from production:
```
Fatal Exception: java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: /storage/emulated/0/WhatsApp Business/Media/WhatsApp Business Documents/doc04757020210204182259.pdf
       at android.app.DownloadManager$Request.<init>(DownloadManager.java:461)
       at com.helpcrunch.library.utils.upload_download.b.a(b.java:52)
       at com.helpcrunch.library.e.b.b.a.a(a.java:988)
       at com.helpcrunch.library.e.b.b.a.a(a.java:75)
       at com.helpcrunch.library.e.b.b.a$s0.a(a.java:936)
       at com.helpcrunch.library.f.f.b$f.a(b.java:153)
       at com.helpcrunch.library.f.f.a$a$a.onClick(a.java:64)
       at android.view.View.performClick(View.java:7217)
       at android.view.View.performClickInternal(View.java:7191)
       at android.view.View.access$3500(View.java:828)
       at android.view.View$PerformClick.run(View.java:27679)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8347)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

`implementation "com.helpcrunch:chat-sdk:3.0.7"`
**Android:** 10
**Device:** HUAWEI nova 5T

**Comment by TalbotGooday** [comment]
Thanks for the report! Will be fixed in the next release!
