### ISSUE TITLE
OutOfMemoryErrors in 3.0.8-alpha.02

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#26]
Hi,

I got lots of OOM errors when using the alpha version of the lib.
com.helpcrunch:chat-sdk:3.0.8-alpha.02

Here's one of them:

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 2064 byte allocation with 808 free bytes and 808B until OOM, target footprint 536870912, growth limit 536870912
       at com.google.gson.stream.JsonReader.<init>(JsonReader.java:239)
       at com.google.gson.Gson.newJsonReader(Gson.java:767)
       at com.google.gson.Gson.fromJson(Gson.java:896)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)
       at com.helpcrunch.library.d.d.c.d.b.e(SpSecureRepository.kt:3)
       at com.helpcrunch.library.d.b.d.b.intercept(RegistrationInterceptor.kt:3)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at com.helpcrunch.library.d.b.d.a.intercept(HostSelectionInterceptor.kt:15)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by TalbotGooday** [comment]
Thanks for the report! Can you please tell me the name of your organization and how often this problem occurs?

**Comment by RKSharma89** [comment]
We are facing the same issue. Is there any update about the issue?

**Comment by TalbotGooday** [comment]
Fixed in version 3.0.8
