### ISSUE TITLE
NPE: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.o0(int)'

### ISSUE THREAD

**Issue by nostra13** [helpcrunch/android-sdk-demo#31]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.o0(int)' on a null object reference
       at com.helpcrunch.library.e.b.b.a$e0.run(a.java:486)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

`implementation "com.helpcrunch:chat-sdk:3.0.7"`
**Android:** 10, 11
**Device:** MI 8, HONOR 10i, Redmi Note 8T,  P30 Pro, Galaxy S20+, KB2001, Mi 9 SE, Galaxy A71, AC2001, HUAWEI P smart Z

**Comment by TalbotGooday** [comment]
Thanks for the report! It's fixed in the latest **RC** versions
