### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#37]
We got lots of errors when using the latest stable release 3.0.8

Fatal Exception: java.lang.StackOverflowError: stack size 1043KB
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at java.security.Provider$Service.newInstance(Provider.java:1635)
       at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
       at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
       at java.security.Security.getImpl(Security.java:628)
       at java.security.MessageDigest.getInstance(MessageDigest.java:197)
       at okio.ByteString.digest$okio(ByteString.java:81)
       at okio.ByteString.md5(ByteString.java:72)
       at okhttp3.Cache$Companion.key(Cache.java:699)
       at okhttp3.Cache.get$okhttp(Cache.java:169)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:47)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at com.helpcrunch.library.g.a.intercept(a.java:15)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall.execute(RealCall.java:154)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:108)
       at com.helpcrunch.library.g.c.a(c.java:36)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:74)
       at com.helpcrunch.library.g.c.intercept(c.java:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at com.helpcrunch.library.g.a.intercept(a.java:15)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by TalbotGooday** [comment]
Thanks for the report! We will check this error and it will be fixed in the new version

**Comment by Mahmoood** [comment]
Hi,

When do you expect you'll deploy the new version?
Because that bug occurs a lot, Should we wait or revert to the previous version!

**Comment by TalbotGooday** [comment]
It might be because you are using a newer version of okhttp not the  3.12.12. We will need time to figure out why this is happening. Try it now please follow the instructions in ReadMe and use strictly version 3.12.12.

**Comment by Mahmoood** [comment]
Yes, we're using the Okhttp v4.
I think you need to support both versions.

**Comment by TalbotGooday** [comment]
Yes, it's a good idea, but we can't do it due to lack of developers :D

I'll remove a strictly OkHttp implementation and hope this will help

**Comment by Mahmoood** [comment]
Actually, we're planning to remove the whole service from our apps.
Because it causes lots of issues which means lots of 1 star of users' reviews.
