### ISSUE TITLE
RuntimeExecutionException

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#38]
SDK version 3.0.8
We got some errors on Android 10 devices (Samsung, Xaomi, ...)

Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
       at com.google.android.gms.tasks.zzu.getResult(zzu.java:15)
       at com.helpcrunch.library.t1.a$a.onComplete(a.java:1)
       at com.google.android.gms.tasks.zzj.run(zzj.java:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7561)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by TalbotGooday** [comment]
Thanks for the report! The bug will be fixed in the new version

**Comment by Mahmoood** [comment]
Hi,

When do you expect you'll deploy the new version?
Because that bug occurs a lot, Should we wait or revert to the previous version!
