### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#39]
SDK v3.0.8

Fatal Exception: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available

com.helpcrunch.library.to.x Dispatcher
       at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:164)
       at okhttp3.Dispatcher.finished(Dispatcher.java:213)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:203)
       at okhttp3.Dispatcher.finished$okhttp(Dispatcher.java:203)
       at okhttp3.internal.connection.RealCall.execute(RealCall.java:156)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:108)
       at com.helpcrunch.library.g.c.a(c.java:36)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:74)
       at com.helpcrunch.library.g.c.intercept(c.java:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at com.helpcrunch.library.g.a.intercept(a.java:15)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
       
 It occurs a lot, all cases happen when the app is in the background (not foregrounded).

**Comment by nostra13** [comment]
I have the same issue. A lot of OOMs after app is going to background. And there is no single stacktrace for these crashes. There are a lot of crashes with different stacktraces, so Crashlytics can't  group them into single OOM crash.

**Comment by Mahmoood** [comment]
What does HelpCrunch do in the background?
So, why does the SDK fire an HTTP request(s)?

**Comment by TalbotGooday** [comment]
@Mahmoood @nostra13 We are not doing anything illegal in the background. :sweat_smile: It looks like it's just a ping to check the customer's online state that causes an error like this. I hope my guess is correct and we fix it

**Comment by Mahmoood** [comment]
@nostra13 Hi, Are you still seeing this OOM issue when the app is in the background?

**Comment by nostra13** [comment]
@Mahmoood No, using 3.2.0.
