### ISSUE TITLE
StackOverflowError - 2

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#40]
SDK v3.0.8
It occurs a lot when the app is in the background.

Fatal Exception: java.lang.StackOverflowError: stack size 1043KB
       at okhttp3.HttpUrl$Companion.defaultPort(HttpUrl.java:1573)
       at okhttp3.HttpUrl$Builder.effectivePort(HttpUrl.java:972)
       at okhttp3.HttpUrl$Builder.toString(HttpUrl.java:1217)
       at okhttp3.HttpUrl.uri(HttpUrl.java:409)
       at okhttp3.internal.connection.RouteSelector$resetNextProxy$1.invoke(RouteSelector.java:102)
       at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.java:113)
       at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.java:53)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:202)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.java:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at com.helpcrunch.library.g.a.intercept(a.java:15)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall.execute(RealCall.java:154)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:108)
       at com.helpcrunch.library.g.c.a(c.java:36)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:49)
       at com.helpcrunch.library.g.c.a(c.java:74)
       at com.helpcrunch.library.g.c.intercept(c.java:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at com.helpcrunch.library.g.a.intercept(a.java:15)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by TalbotGooday** [comment]
Copy of https://github.com/helpcrunch/android-sdk-demo/issues/37
