### ISSUE TITLE
Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#41]
I got Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException
java.io.IOException: SERVICE_NOT_AVAILABLE on devices running Android 10 when using the SDK v3.0.8

Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
       at com.google.android.gms.tasks.zzu.getResult(zzu.java:15)
       at com.helpcrunch.library.t1.a$a.onComplete(a.java:1)
       at com.google.android.gms.tasks.zzj.run(zzj.java:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.google.android.gms.internal.tasks.zzb.dispatchMessage(zzb.java:6)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1087)

**Comment by TalbotGooday** [comment]
The crash is already fixed. Please, update version to the 3.1.1.

**Comment by Mahmoood** [comment]
Thanks.

How can we know the releases you made and what every release includes?
There's nothing in the releases section here in Github.

**Comment by TalbotGooday** [comment]
This information will be updated when higher priority tasks are completed. You can find out the latest version from the badge posted in the [README](https://github.com/helpcrunch/android-sdk-demo#readme) 
<img alt="Maven Central" src="https://maven-badges.herokuapp.com/maven-central/com.helpcrunch/chat-sdk/badge.svg" /></a>
