### ISSUE TITLE
java.io.IOException: TOO_MANY_REGISTRATIONS

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#43]
Hi,

Using the SDK v3.1.1 and forcing OkHttp for version 3.12.12
I got this issue:

Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: java.io.IOException: TOO_MANY_REGISTRATIONS
       at com.google.android.gms.tasks.zzu.getResult(zzu.java:15)
       at com.helpcrunch.library.t1.a$a.onComplete(a.java:1)
       at com.google.android.gms.tasks.zzj.run(zzj.java:4)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.google.android.gms.internal.tasks.zzb.dispatchMessage(zzb.java:6)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by TalbotGooday** [comment]
I'm starting to wonder how you can break something that has never broken :sweat_smile: 
Anyway, thanks for the report. I will check it :+1:
