### ISSUE TITLE
IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by nostra13** [helpcrunch/android-sdk-demo#47]
Crash from production.
```
Fatal Exception: java.lang.IllegalStateException: FragmentManager is already executing transactions
       at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1931)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1996)
       at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:661)
       at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:436)
       at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:192)
       at com.helpcrunch.library.ui.screens.main.HelpCrunchMainActivity.onBackPressed(HelpCrunchMainActivity.java:3)
       at com.helpcrunch.library.ui.screens.main.HelpCrunchMainActivity.e(HelpCrunchMainActivity.java:1)
       at com.helpcrunch.library.d0.a.e(a.java:9)
       at com.helpcrunch.library.d0.a.a(a.java:2407)
       at com.helpcrunch.library.d0.a.a(a.java:6)
       at com.helpcrunch.library.d0.a$w.a(a.java:3)
       at com.helpcrunch.library.d0.a$w.invoke(a.java:1)
       at com.helpcrunch.library.d0.c.onChanged(c.java:2)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
       at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
       at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
       at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:88)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3028)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7986)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

`implementation "com.helpcrunch:chat-sdk:3.1.3"`

**Device:** Galaxy S10e
**Android:** 10

**Comment by TalbotGooday** [comment]
Thanks for the reporting!
