### ISSUE TITLE
SecurityException: Permission Denial (requires READ_EXTERNAL_STORAGE or grantUriPermission())

### ISSUE THREAD

**Issue by nostra13** [helpcrunch/android-sdk-demo#52]
Crash from prod:
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:354)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```
```
Caused by java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=3317, uid=10069 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
       at android.os.Parcel.createException(Parcel.java:1950)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:418)
       at android.content.ContentResolver.query(ContentResolver.java:803)
       at android.content.ContentResolver.query(ContentResolver.java:753)
       at android.content.ContentResolver.query(ContentResolver.java:711)
       at com.helpcrunch.library.utils.file_picker.i.a(i.java:20)
       at com.helpcrunch.library.utils.file_picker.i.doInBackground(i.java:1)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

`implementation "com.helpcrunch:chat-sdk:3.1.5"`

**Android:** 9
**Device:**  Pixel 3 XL

**Comment by TalbotGooday** [comment]
Thanks for the reporting!

**Comment by Appverse2023** [comment]
@TalbotGooday Can you please let me it's solution, I am facing same issue

**Comment by TalbotGooday** [comment]
@Appverse2023 hi! I still can't reproduce this bug. If you have any additional information about this, I would be very grateful if you could share it.

**Comment by Appverse2023** [comment]
Hi @TalbotGooday, I am also not able to reproduced but some of my user facing this, I can provide you the logs from firebase.

Logs:-
Fatal Exception: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/video/media from pid=12413, uid=10463 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
       at android.os.Parcel.createException(Parcel.java:1950)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
       at android.content.ContentResolver.query(ContentResolver.java:932)
       at android.content.ContentResolver.query(ContentResolver.java:856)
       at android.content.ContentResolver.query(ContentResolver.java:814)
