### ISSUE TITLE
Missing type parameter.

### ISSUE THREAD

**Issue by nostra13** [helpcrunch/android-sdk-demo#57]
Crash on app start:
```
Caused by java.lang.RuntimeException: Missing type parameter.
       at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(TypeToken.java:84)
       at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:62)
       at w1.d$b.<init>(SimpleEmojiHelper.kt:1)
       at ul.d$b.$r8$init$synthetic(d.java:1)
       at w1.d.a(d.java:8)
       at w1.c.a(c.java:1)
       at com.helpcrunch.library.core.HelpCrunch.a(HelpCrunch.kt:27)
       at com.helpcrunch.library.core.HelpCrunch.initService$helpcrunch_release(HelpCrunch.kt:35)
       at com.helpcrunch.library.core.HelpCrunchInitProvider$a.a(HelpCrunchInitProvider.java:3)
       at com.helpcrunch.library.core.HelpCrunchInitProvider.onCreate(HelpCrunchInitProvider.kt:3)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at com.helpcrunch.library.core.HelpCrunchInitProvider.attachInfo(HelpCrunchInitProvider.kt:5)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8069)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7605)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7489)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7446)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

`implementation "com.helpcrunch:chat-sdk:3.2.3-rc-01"`
`implementation "com.google.code.gson:gson:2.9.0"`

**Samsung Galaxy A51
Android 11**

**Comment by TalbotGooday** [comment]
Thanks for reporting!
