### ISSUE TITLE
Unable to get provider HelpCrunchInitProvider: Missing type parameter

### ISSUE THREAD

**Issue by nostra13** [helpcrunch/android-sdk-demo#59]
Crash on app start after upgrade to 
`implementation "androidx.activity:activity-ktx:1.5.0"`
`implementation "androidx.fragment:fragment-ktx:1.5.0"`
`implementation "androidx.navigation:navigation-fragment-ktx:2.5.0"`
`implementation "androidx.navigation:navigation-ui-ktx:2.5.0"`

```
Fatal Exception: java.lang.RuntimeException: Unable to get provider com.helpcrunch.library.core.HelpCrunchInitProvider: java.lang.RuntimeException: Missing type parameter.
       at android.app.ActivityThread.installProvider(ActivityThread.java:8074)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7605)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7489)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7446)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```
```
Caused by java.lang.RuntimeException: Missing type parameter.
       at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(TypeToken.java:84)
       at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:62)
       at w1.d$b.<init>(SimpleEmojiHelper.kt)
       at w1.d.a(d.java:8)
       at w1.c.a(c.java:1)
       at com.helpcrunch.library.core.HelpCrunch.a(HelpCrunch.kt:27)
       at com.helpcrunch.library.core.HelpCrunch.initService$helpcrunch_release(HelpCrunch.kt:35)
       at com.helpcrunch.library.core.HelpCrunchInitProvider$a.a(HelpCrunchInitProvider.java:3)
       at com.helpcrunch.library.core.HelpCrunchInitProvider.onCreate(HelpCrunchInitProvider.kt:3)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at com.helpcrunch.library.core.HelpCrunchInitProvider.attachInfo(HelpCrunchInitProvider.kt:5)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8069)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7605)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7489)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7446)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

implementation "com.helpcrunch:chat-sdk:3.2.3-rc-01"

**Comment by TalbotGooday** [comment]
Thanks for reporting! It's weird to be honest. Could you please check on 3.2.3-rc-04?

**Comment by TalbotGooday** [comment]
@nostra13 Did you do any manipulations with the proguard?

**Comment by nostra13** [comment]
**3.2.3-rc-04** breaks my code compilation. Looks like it became Java-written lib instead of Kotlin.

What do you mean by "manipulations with the proguard"?

**Comment by TalbotGooday** [comment]
Oh god. Something seems to be broken after gradle update

**Comment by TalbotGooday** [comment]
@nostra13 please check 3.2.3-rc-07. Everything should be fine including #58, #57, #51
