### ISSUE TITLE
Firebase Error in production

### ISSUE THREAD

**Issue by francescogatto** [helpcrunch/android-sdk-demo#62]
HI

I have this error in crashlytics: 

```
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.5). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

```
```
Caused by java.lang.NoSuchMethodError: No virtual method object()Lcom/helpcrunch/chat/jw1; in class Lcom/helpcrunch/chat/jw1; or its super classes (declaration of 'com.helpcrunch.chat.jw1' appears in base.apk!classes3.dex)
       at com.google.firebase.database.util.JsonMapper.serializeJsonValue(JsonMapper.java:69)
       at com.google.firebase.database.util.JsonMapper.serializeJsonValue(JsonMapper.java:58)
       at com.google.firebase.database.util.JsonMapper.serializeJson(JsonMapper.java:38)
       at com.google.firebase.database.connection.WebsocketConnection.send(WebsocketConnection.java:234)
       at com.google.firebase.database.connection.Connection.sendData(Connection.java:246)
       at com.google.firebase.database.connection.Connection.sendRequest(Connection.java:120)
       at com.google.firebase.database.connection.PersistentConnectionImpl.sendSensitive(PersistentConnectionImpl.java:1427)
       at com.google.firebase.database.connection.PersistentConnectionImpl.sendAction(PersistentConnectionImpl.java:1414)
       at com.google.firebase.database.connection.PersistentConnectionImpl.sendStats(PersistentConnectionImpl.java:1366)
       at com.google.firebase.database.connection.PersistentConnectionImpl.sendConnectStats(PersistentConnectionImpl.java:1409)
       at com.google.firebase.database.connection.PersistentConnectionImpl.onReady(PersistentConnectionImpl.java:365)
       at com.google.firebase.database.connection.Connection.onConnectionReady(Connection.java:220)
       at com.google.firebase.database.connection.Connection.onHandshake(Connection.java:213)
       at com.google.firebase.database.connection.Connection.onControlMessage(Connection.java:185)
       at com.google.firebase.database.connection.Connection.onMessage(Connection.java:135)
       at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:259)
       at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:306)
       at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:34)
       at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:86)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
```

**Comment by TalbotGooday** [comment]
This is probably another compatibility bug.  Please compare dependency versions with our dependencies
https://github.com/helpcrunch/android-sdk-demo/blob/master/DEPENDENCY_LIST.md

**Comment by francescogatto** [comment]
Hi! HEre my dependencies for firebase and still have crashes! Please is very important

 implementation platform('com.google.firebase:firebase-bom:29.1.0')
    implementation 'com.google.firebase:firebase-inappmessaging-display-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-config-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-database-ktx'
    implementation 'com.google.firebase:firebase-dynamic-links-ktx'
    implementation 'com.google.firebase:firebase-storage-ktx'
    implementation 'com.google.firebase:firebase-firestore-ktx'

**Comment by TalbotGooday** [comment]
Please try to update HelpCrunch version to 3.2.3-rc-07 and Firebase BOM to 30.2.0. I hope it helps

**Comment by francescogatto** [comment]
I will do in the next release.

Il Ven 29 Lug 2022, 09:55 Alexey Mostovoy ***@***.***> ha
scritto:
