### ISSUE TITLE
Realtime database exception

### ISSUE THREAD

**Issue by francescogatto** [helpcrunch/android-sdk-demo#64]
While trying to use firebase realtime database in release mode (so minifyenabled true), i have this exception. 
I use the 30.2.0 firebase BOM like the last sdk version 

```
Uncaught exception in Firebase Database runloop (20.0.5). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
    java.lang.NoSuchMethodError: No virtual method object()Lcom/helpcrunch/library/ey1; in class Lcom/helpcrunch/library/ey1; or its super classes (declaration of 'com.helpcrunch.library.ey1' appears in /data/app/~~91pGC3XBaHJFheMESbjnzA==/na-StKfQ5gKoaM8lUKsKersnw==/base.apk!classes3.dex)
        at com.helpcrunch.library.b02.e(SourceFile:5)
        at com.helpcrunch.library.b02.d(SourceFile:60)
        at com.helpcrunch.library.b02.c(Unknown Source:0)
        at com.helpcrunch.library.g55.v(SourceFile:4)
        at com.helpcrunch.library.l40.l(SourceFile:44)
        at com.helpcrunch.library.l40.m(SourceFile:16)
        at com.helpcrunch.library.z83.z0(SourceFile:31)
        at com.helpcrunch.library.z83.q0(Unknown Source:1)
        at com.helpcrunch.library.z83.A0(SourceFile:24)
        at com.helpcrunch.library.z83.u0(SourceFile:76)
        at com.helpcrunch.library.z83.g(SourceFile:32)
        at com.helpcrunch.library.l40.e(SourceFile:25)
        at com.helpcrunch.library.l40.i(SourceFile:45)
        at com.helpcrunch.library.l40.g(SourceFile:102)
        at com.helpcrunch.library.l40.a(SourceFile:45)
        at com.helpcrunch.library.g55.j(SourceFile:72)
        at com.helpcrunch.library.g55.o(SourceFile:24)
        at com.helpcrunch.library.g55.f(Unknown Source:0)
        at com.helpcrunch.library.g55$e$b.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by TalbotGooday** [comment]
@francescogatto Hi! Could you please share the version of your `firebase-bom`? We have version `30.2.0`. I am 99% sure that you will avoid this crash if you will use the same version of `firebase-bom`
