### ISSUE TITLE
Crash on HelpCrunch 3.2.5/3.2.6

### ISSUE THREAD

**Issue by VMitinDev** [helpcrunch/android-sdk-demo#67]
Crash when trying to open chat  (com.helpcrunch:chat-sdk:3.2.6)

java.lang.RuntimeException: Failed to invoke public com.helpcrunch.library.kt6() with no args
                                                                                                    	at com.helpcrunch.library.lm0.i(SourceFile:45)
                                                                                                    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(SourceFile:16)
                                                                                                    	at com.google.gson.internal.bind.a.a(SourceFile:3)
                                                                                                    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(SourceFile:48)
                                                                                                    	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(SourceFile:6)
                                                                                                    	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(SourceFile:1)
                                                                                                    	at retrofit2.OkHttpCall.parseResponse(SourceFile:54)
                                                                                                    	at retrofit2.OkHttpCall$1.onResponse(SourceFile:3)
                                                                                                    	at com.helpcrunch.library.uj2.onResponse(SourceFile:17)
                                                                                                    	at com.helpcrunch.library.e14$a.run(SourceFile:59)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.NullPointerException
                                                                                                    	at com.helpcrunch.library.kt6.<init>(Unknown Source:1)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at com.helpcrunch.library.lm0.i(SourceFile:10)
                                                                                                    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(SourceFile:16) 
                                                                                                    	at com.google.gson.internal.bind.a.a(SourceFile:3) 
                                                                                                    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(SourceFile:48) 
                                                                                                    	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(SourceFile:6) 
                                                                                                    	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(SourceFile:1) 
                                                                                                    	at retrofit2.OkHttpCall.parseResponse(SourceFile:54) 
                                                                                                    	at retrofit2.OkHttpCall$1.onResponse(SourceFile:3) 
                                                                                                    	at com.helpcrunch.library.uj2.onResponse(SourceFile:17) 
                                                                                                    	at com.helpcrunch.library.e14$a.run(SourceFile:59) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by TalbotGooday** [comment]
Hi, @VMitinDev. Thanks for the reporting! Could you please share a code snipped where the crash happened?

**Comment by VMitinDev** [comment]
Oh, I just start a chat 

HelpCrunch.showChatScreen(
                    options = HCOptions
                        .Builder()
                        .setTheme(
                            HCTheme
                                .Builder(
                                    when (ctx.isDarkTheme()) {
                                        true -> HCTheme.Type.DARK
                                        false -> HCTheme.Type.DEFAULT
                                    }
                                )
                                .build()
                        )
                        .build(),
                    callback = object : Callback<Any?>() {
                        override fun onError(message: String) {
                            ...
                        }
                    }
                )
                
In this case, the chat screen opens with infinity loader. 
Downgrade to version 3.2.2 fix the problem

**Comment by TalbotGooday** [comment]
@VMitinDev  tried your code on Android 12. Can't reproduce. Could you please give me some more information so I can reproduce the bug

**Comment by VMitinDev** [comment]
Hi! 

My dependencies tree 
+--- com.helpcrunch:chat-sdk:3.2.6
|    +--- com.google.android.material:material:1.5.0 -> 1.7.0 (*)
|    +--- androidx.appcompat:appcompat:1.2.0 -> 1.5.1 (*)
|    +--- androidx.core:core-ktx:1.3.2 -> 1.9.0 (*)
|    +--- androidx.recyclerview:recyclerview:1.2.1 (*)
|    +--- com.google.firebase:firebase-bom:30.4.1 (*)
|    +--- com.google.firebase:firebase-messaging -> 23.0.8
|    |    +--- androidx.annotation:annotation:1.2.0 -> 1.3.0
|    |    +--- com.google.android.datatransport:transport-api:3.0.0 (*)
|    |    +--- com.google.android.datatransport:transport-backend-cct:3.1.7 (*)
|    |    +--- com.google.android.datatransport:transport-runtime:3.1.7 (*)
|    |    +--- com.google.android.gms:play-services-base:18.0.1 (*)
|    |    +--- com.google.android.gms:play-services-basement:18.1.0 (*)
|    |    +--- com.google.android.gms:play-services-cloud-messaging:17.0.1
|    |    |    +--- com.google.android.gms:play-services-basement:18.0.0 -> 18.1.0 (*)
|    |    |    \--- com.google.android.gms:play-services-tasks:18.0.0 -> 18.0.1 (*)
|    |    +--- com.google.android.gms:play-services-stats:17.0.2 (*)
|    |    +--- com.google.android.gms:play-services-tasks:18.0.1 (*)
|    |    +--- com.google.errorprone:error_prone_annotations:2.9.0
|    |    +--- com.google.firebase:firebase-common:20.1.2 (*)
|    |    +--- com.google.firebase:firebase-components:17.0.1 (*)
|    |    +--- com.google.firebase:firebase-datatransport:18.1.6 (*)
|    |    +--- com.google.firebase:firebase-encoders:17.0.0 (*)
|    |    +--- com.google.firebase:firebase-encoders-json:18.0.0 (*)
|    |    +--- com.google.firebase:firebase-encoders-proto:16.0.0 (*)
|    |    +--- com.google.firebase:firebase-iid-interop:17.1.0
|    |    |    +--- com.google.android.gms:play-services-basement:17.0.0 -> 18.1.0 (*)
|    |    |    \--- com.google.android.gms:play-services-tasks:17.0.0 -> 18.0.1 (*)
|    |    +--- com.google.firebase:firebase-installations:17.0.2 (*)
|    |    +--- com.google.firebase:firebase-installations-interop:17.0.2 (*)
|    |    \--- com.google.firebase:firebase-measurement-connector:19.0.0 (*)
|    +--- com.google.code.gson:gson:2.9.0
|    +--- com.squareup.retrofit2:retrofit:2.9.0 (*)
|    +--- com.squareup.retrofit2:converter-gson:2.9.0 (*)
|    +--- com.squareup.okhttp3:okhttp:3.12.13 -> 4.9.1 (*)
|    +--- com.squareup.okhttp3:logging-interceptor:3.12.13 -> 4.2.1
|    |    \--- com.squareup.okhttp3:okhttp:4.2.1 -> 4.9.1 (*)
|    +--- com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2
|    |    +--- com.squareup.retrofit2:retrofit:2.4.0 -> 2.9.0 (*)
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.0-rc-57 -> 1.7.10 (*)
|    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:0.26.1-eap13 -> 1.6.4 (*)
|    +--- com.localebro:okhttpprofiler:1.0.8
|    +--- androidx.room:room-runtime:2.4.2 -> 2.4.3 (*)
|    +--- androidx.room:room-ktx:2.4.2 -> 2.4.3 (*)
|    +--- androidx.emoji:emoji:1.1.0
|    |    \--- androidx.core:core:1.3.0 -> 1.9.0 (*)
|    +--- androidx.emoji:emoji-appcompat:1.1.0
|    |    +--- androidx.emoji:emoji:1.1.0 (*)
|    |    \--- androidx.appcompat:appcompat:1.1.0 -> 1.5.1 (*)
|    +--- io.coil-kt:coil:1.4.0 (*)
|    +--- io.coil-kt:coil-gif:1.4.0
|    |    \--- io.coil-kt:coil-base:1.4.0 (*)
|    +--- io.coil-kt:coil-svg:1.4.0
|    |    \--- io.coil-kt:coil-base:1.4.0 (*)
|    +--- io.noties.markwon:core:4.6.2
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
|    |    \--- com.atlassian.commonmark:commonmark:0.13.0
|    +--- io.noties.markwon:html:4.6.2
|    |    \--- io.noties.markwon:core:4.6.2 (*)
|    +--- io.noties.markwon:inline-parser:4.6.2
|    |    +--- io.noties.markwon:core:4.6.2 (*)
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
|    |    \--- com.atlassian.commonmark:commonmark:0.13.0
|    +--- io.noties.markwon:image:4.6.2
|    |    \--- io.noties.markwon:core:4.6.2 (*)
|    +--- androidx.work:work-runtime-ktx:2.7.1 (*)
|    +--- androidx.lifecycle:lifecycle-extensions:2.2.0
|    |    +--- androidx.lifecycle:lifecycle-runtime:2.2.0 -> 2.5.1 (*)
|    |    +--- androidx.arch.core:core-common:2.1.0 (*)
|    |    +--- androidx.arch.core:core-runtime:2.1.0 (*)
|    |    +--- androidx.fragment:fragment:1.2.0 -> 1.5.4 (*)
|    |    +--- androidx.lifecycle:lifecycle-common:2.2.0 -> 2.5.1 (*)
|    |    +--- androidx.lifecycle:lifecycle-livedata:2.2.0 -> 2.5.1 (*)
|    |    +--- androidx.lifecycle:lifecycle-process:2.2.0 -> 2.4.1
|    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.4.1 -> 2.5.1 (*)
|    |    |    +--- androidx.startup:startup-runtime:1.1.1
|    |    |    \--- androidx.annotation:annotation:1.2.0 -> 1.3.0
|    |    +--- androidx.lifecycle:lifecycle-service:2.2.0
|    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.2.0 -> 2.5.1 (*)
|    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.2.0 -> 2.5.1 (*)
|    +--- androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0 -> 2.5.1 (*)
|    +--- androidx.lifecycle:lifecycle-livedata-ktx:2.4.0 -> 2.5.1 (*)
|    +--- io.insert-koin:koin-android:3.1.5
|    |    +--- io.insert-koin:koin-core:3.1.5
|    |    |    \--- io.insert-koin:koin-core-jvm:3.1.5
|    |    |         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31 -> 1.7.10
|    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 -> 1.7.10 (*)
|    |    +--- androidx.lifecycle:lifecycle-extensions:2.2.0 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 -> 1.7.10 (*)
|    +--- com.github.TalbotGooday:Android-Oembed-Video:0.2.1
|    +--- com.github.chrisbanes:PhotoView:2.3.0
|    +--- com.github.duanhong169:drawabletoolbox:1.0.7
|    +--- com.github.TalbotGooday:AvatarView:0.1.1
|    |    +--- androidx.core:core-ktx:1.7.0 -> 1.9.0 (*)
|    |    +--- androidx.appcompat:appcompat:1.4.1 -> 1.5.1 (*)
|    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2 -> 1.6.4 (*)
|    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2 -> 1.6.4 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30 -> 1.7.10 (*)
|    +--- io.socket:socket.io-client:1.0.0
|    |    +--- io.socket:engine.io-client:1.0.0
|    |    |    +--- com.squareup.okhttp3:okhttp:3.8.1 -> 4.9.1 (*)
|    |    |    \--- org.json:json:20090211
|    |    \--- org.json:json:20090211
|    +--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2 -> 1.6.4 (*)
|    +--- androidx.databinding:viewbinding:7.0.4 -> 7.3.0 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 -> 1.7.10 (*)

**Comment by VMitinDev** [comment]
Also, I have create a blank project. Add as dependency only `implementation 'com.helpcrunch:chat-sdk:3.2.6'` and run the release app. I have the same error on the Android 13. 

I can't update the SDK for using the chatbot feature. So, please, help me

**Comment by TalbotGooday** [comment]
@VMitinDev could you please share this "blank project" on GitHub so I can check it?

**Comment by VMitinDev** [comment]
@TalbotGooday https://github.com/VMitinDev/Test_HC

**Comment by TalbotGooday** [comment]
Thanks 😊

**Comment by VMitinDev** [comment]
@TalbotGooday btw the problem in versions 3.2.3+

I need to update to 3.2.3 to use chatbot. So, I hope you will help me.

**Comment by TalbotGooday** [comment]
@VMitinDev hi! Any updates with this bug?
