### ISSUE TITLE
Camera permission

### ISSUE THREAD

**Issue by mayada1994** [helpcrunch/android-sdk-demo#70]
The camera permission request isn't triggered after the storage permission request, so when a user tries to take a photo the app crashes with the following exception.
`java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list hasLabel(0) {U(content)}} (has extras) } from ProcessRecord{247ba78 11398:com.helpcrunch.demo/u0a173} (pid=11398, uid=10173) with revoked permission android.permission.CAMERA
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2392)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2334)
                                                                                                    	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2284)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5404)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
                                                                                                    	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:766)
                                                                                                    	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:241)
                                                                                                    	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:237)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$3.launch(ActivityResultRegistry.java:246)
                                                                                                    	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
                                                                                                    	at androidx.fragment.app.FragmentManager.launchStartActivityForResult(FragmentManager.java:2814)
                                                                                                    	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1502)
                                                                                                    	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1471)
                                                                                                    	at com.helpcrunch.library.h8.g(MediaFolderPickerFragment.kt:4)
                                                                                                    	at com.helpcrunch.library.y2$c.a(FolderGridAdapter.kt:97)
                                                                                                    	at com.helpcrunch.library.y2$c.$r8$lambda$W0Vzm3WguA4ug3xv7lof7Q4uxf8(Unknown Source:0)
                                                                                                    	at com.helpcrunch.library.y2$c$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7441)
                                                                                                    	at android.view.View.performClickInternal(View.java:7418)
                                                                                                    	at android.view.View.access$3700(View.java:835)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28676)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1047)
                                                                                                    	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:975)
                                                                                                    	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:665)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1201)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1173)`

**Comment by TalbotGooday** [comment]
Hi again, @mayada1994! Please tell me, what version of HelpCrunch SDK and what version of Android?

**Comment by mayada1994** [comment]
HelpCrunch SDK 3.2.6. I checked the issue on a Pixel 3 emulator with Android 11 and Xiaomi Redmi Note 7 with Android 10. It's reproduced on both devices.

**Comment by TalbotGooday** [comment]
Hmm... That's weird. Thanks 👍

**Comment by TalbotGooday** [comment]
@mayada1994 Hi! Sorry for the long silence. Checked the logs that you've provided and the SDK logic and I'm 100% sure that this crash is because of the Camera app not 'cause of the SDK.  

As you can see from logs the crash is here
```
starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list hasLabel(0) {U(content)}} (has extras) }
```
and it's because the Android system revoked `android.permission.CAMERA` permission from the Camera app. 
Long story short we can't do anything with this. This is a Camera app bug :sweat_smile:
