### ISSUE TITLE
Crashes when users try to attach an image

### ISSUE THREAD

**Issue by yaroslav-v** [helpcrunch/android-sdk-demo#72]
Hi guys!

There is a crash when users try to attach an image to the chat on the latest available version 3.2.6.

Steps to reproduce:
1. Open a chat
2. Press the attach button
3. Select the photo option
4. Choose a picture (or shoot a new one)
5. At the moment you've chosen the picture it crashes

You can check the crash log bellow:

`E  FATAL EXCEPTION: main
                                         Process: com.test.app, PID: 6381
                                         java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/CoroutineWorker;
                                         	at com.helpcrunch.library.i9$c.b(Module.kt:1)
                                         	at com.helpcrunch.library.i9$c.a(Module.kt:1)
                                         	at com.helpcrunch.library.i9$c$a.a(Module.kt:146)
                                         	at com.helpcrunch.library.i9$c$a.invoke(Module.kt:1)
                                         	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
                                         	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                         	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                         	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
                                         	at org.koin.mp.KoinPlatformTools.synchronized(PlatformToolsJVM.kt:20)
                                         	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
                                         	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
                                         	at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
                                         	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
                                         	at org.koin.core.scope.Scope.get(Scope.kt:204)
                                         	at com.helpcrunch.library.i9$j$d.a(Module.kt:104)
                                         	at com.helpcrunch.library.i9$j$d.invoke(Module.kt:1)
                                         	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
                                         	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
                                         	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
                                         	at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
                                         	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
                                         	at org.koin.core.scope.Scope.get(Scope.kt:204)
                                         	at com.helpcrunch.library.s5$a.invoke(KoinComponent.kt:17)
                                         	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                         	at com.helpcrunch.library.s5.g(HelpCrunchRouter.kt:1)
                                         	at com.helpcrunch.library.s5.a(HelpCrunchRouter.kt:2)
                                         	at com.helpcrunch.library.core.HelpCrunch.initService$helpcrunch_release(HelpCrunch.kt:37)
                                         	at com.helpcrunch.library.core.HelpCrunchInitProvider$a.a(HelpCrunchInitProvider.kt:3)
                                         	at com.helpcrunch.library.core.HelpCrunchInitProvider.onCreate(HelpCrunchInitProvider.kt:3)
                                         	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
                                         	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
                                         	at com.helpcrunch.library.core.HelpCrunchInitProvider.attachInfo(HelpCrunchInitProvider.kt:5)
                                         	at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
                                         	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
                                         	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
                                         	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
                                         	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
                                         	at android.os.Handler.dispatchMessage(Handler.java:106)
                                         	at android.os.Looper.loop(Looper.java:223)
                                         	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.work.CoroutineWorker" on path: DexPathList[[zip file "/data/app/~~dbIiDcmBboVyy8Qrj7XyJw==/com.test.app-rUApF3w8LvDEgad6xHJrOQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~dbIiDcmBboVyy8Qrj7XyJw==/com.test.app-rUApF3w8LvDEgad6xHJrOQ==/lib/x86_64, /data/app/~~dbIiDcmBboVyy8Qrj7XyJw==/com.test.app-rUApF3w8LvDEgad6xHJrOQ==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                         	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                         	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                         	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                         	at com.helpcrunch.library.i9$c.b(Module.kt:1) 
                                         	at com.helpcrunch.library.i9$c.a(Module.kt:1) 
                                         	at com.helpcrunch.library.i9$c$a.a(Module.kt:146) 
                                         	at com.helpcrunch.library.i9$c$a.invoke(Module.kt:1) 
                                         	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53) 
                                         	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46) 
                                         	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53) 
                                         	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51) 
                                         	at org.koin.mp.KoinPlatformTools.synchronized(PlatformToolsJVM.kt:20) 
                                         	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51) 
                                         	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110) 
                                         	at org.koin.core.scope.Scope.resolveValue(Scope.kt:254) 
                                         	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241) 
                                         	at org.koin.core.scope.Scope.get(Scope.kt:204) 
                                         	at com.helpcrunch.library.i9$j$d.a(Module.kt:104) 
                                         	at com.helpcrunch.library.i9$j$d.invoke(Module.kt:1) 
                                         	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53) 
                                         	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38) 
                                         	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110) 
                                         	at org.koin.core.scope.Scope.resolveValue(Scope.kt:254) 
                                         	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241) 
                                         	at org.koin.core.scope.Scope.get(Scope.kt:204) 
                                         	at com.helpcrunch.library.s5$a.invoke(KoinComponent.kt:17) 
                                         	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
                                         	at com.helpcrunch.library.s5.g(HelpCrunchRouter.kt:1) 
                                         	at com.helpcrunch.library.s5.a(HelpCrunchRouter.kt:2) 
                                         	at com.helpcrunch.library.core.HelpCrunch.initService$helpcrunch_release(HelpCrunch.kt:37) 
                                         	at com.helpcrunch.library.core.HelpCrunchInitProvider$a.a(HelpCrunchInitProvider.kt:3) 
                                         	at com.helpcrunch.library.core.HelpCrunchInitProvider.onCreate(HelpCrunchInitProvider.kt:3) 
                                         	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
                                         	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
                                         	at com.helpcrunch.library.core.HelpCrunchInitProvider.attachInfo(HelpCrunchInitProvider.kt:5) 
                                         	at android.app.ActivityThread.installProvider(ActivityThread.java:7239) 
                                         	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780) 
                                         	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697) 
                                         	at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
                                         	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
                                         	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                         	at android.os.Looper.loop(Looper.java:223) 
                                         	at android.app.ActivityThread.main(ActivityThread.java:7656) 
                                         	at java.lang.reflect.Method.invoke(Native Method) 
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

**Comment by yaroslav-v** [comment]
Well, in this case it's WorkManager.

Regarding the future releases, it's interesting. Could you tell me when you're going to release a new version of SDK with the minimum version elevated to Android 6?

**Comment by TalbotGooday** [comment]
> Could you tell me when you're going to release a new version of SDK with the minimum version elevated to Android 6?

I wish I knew :sweat_smile: 

P.S. No, really, I don't know
