### ISSUE TITLE
Crash on  3.3.7

### ISSUE THREAD

**Issue by zhrmghgws** [helpcrunch/android-sdk-demo#83]
java.lang.NullPointerException
                                                                                                    	at com.helpcrunch.library.ui.screens.chats_list.HcChatsListFragment.y(SourceFile:1)
                                                                                                    	at com.helpcrunch.library.ui.screens.chats_list.HcChatsListFragment.a(SourceFile:10)
                                                                                                    	at com.helpcrunch.library.ui.screens.chats_list.ChatsThresholdWarden$handleChatCreationThreshold$1.onFinish(SourceFile:1)
                                                                                                    	at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8123)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by TalbotGooday** [comment]
Thanks for the reporting!

**Comment by TalbotGooday** [comment]
Anyway, this is known issue. Will be fixed in 3.3.8

**Comment by zhrmghgws** [comment]
3.3.8 when will it be released? Because this error will cause our App to crash,We need to fix this problem as soon as possible



发自我的iPhone


------------------ Original ------------------
From: Alexey Mostovoy ***@***.***&gt;
Date: Tue,Apr 16,2024 3:20 PM
To: helpcrunch/android-sdk-demo ***@***.***&gt;
Cc: zhrmghgws ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [helpcrunch/android-sdk-demo] Crash on  3.3.7 (Issue #83)





 
Anyway, this is known issue. Will be fixed in 3.3.8

**Comment by TalbotGooday** [comment]
@zhrmghgws new version is on testing now. So it will take a day or two

**Comment by zhrmghgws** [comment]
OK，looking forward to it



发自我的iPhone


------------------ Original ------------------
From: Alexey Mostovoy ***@***.***&gt;
Date: Tue,Apr 16,2024 4:00 PM
To: helpcrunch/android-sdk-demo ***@***.***&gt;
Cc: zhrmghgws ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [helpcrunch/android-sdk-demo] Crash on  3.3.7 (Issue #83)





 
@zhrmghgws new version is on testing now. So it will take a day or two

**Comment by TalbotGooday** [comment]
Fixed in 3.3.8
