### ISSUE TITLE
android.content.res.Resources$NotFoundException: Font resource ID #0x7f090006 could not be retrieved.

### ISSUE THREAD

**Issue by valmirtt** [helpcrunch/android-sdk-demo#87]
`FATAL EXCEPTION: main
                                                    Process: br.com.netpos.smartpos.devel, PID: 9235
                                                    android.content.res.Resources$NotFoundException: Font resource ID #0x7f090006 could not be retrieved.
                                                    	at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:573)
                                                    	at androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:414)
                                                    	at com.helpcrunch.library.utils.extensions.ViewKt.a(SourceFile:236)
                                                    	at com.helpcrunch.library.utils.extensions.ViewKt.a(SourceFile:10)
                                                    	at com.helpcrunch.library.ui.screens.chats_list.adapters.ChatsAdapter$ChatHolder.a(SourceFile:555)
                                                    	at com.helpcrunch.library.ui.screens.chats_list.adapters.ChatsAdapter$ChatHolder.a(SourceFile:511)
                                                    	at com.helpcrunch.library.ui.screens.chats_list.adapters.ChatsAdapter.onBindViewHolder(SourceFile:8)
                                                    	at com.helpcrunch.library.ui.screens.chats_list.adapters.ChatsAdapter.onBindViewHolder(SourceFile:39)
                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
                                                    	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
                                                    	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
                                                    	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5789)
                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1036)
                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:859)
                                                    	at android.view.Choreographer.doFrame(Choreographer.java:790)
                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1021)
                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                    	at android.os.Looper.loop(Looper.java:214)
                                                    	at android.app.ActivityThread.main(ActivityThread.java:7399)
                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)`

implementation 'com.helpcrunch:chat-sdk:$3.3.9'
Device: Ingenico DX8000
Android: 10

**Comment by TalbotGooday** [comment]
Thanks for the report!
As I understand the device is a payment terminal or something like that. Do you have information about the availability of Google services on it?
Because it is difficult to guarantee that downloadable fonts will be supported on this type of device

**Comment by valmirtt** [comment]
Hi, yes it is a payment terminal. I'm not sure if Google Services are available on this type of device. Is there anything that can be done to support payment terminals that don't have Google Services available if that's the case?

**Comment by TalbotGooday** [comment]
We need to think about this topic. In general, we do not support devices without Google services. Since these are not only font crashes, but even if we fix this issue, there will be a lack of push notifications, for example, which is important for a chat service like our SDK
How critical is this for your business? Do you plan to use your application exclusively on such terminals or is it a small percentage of your clients? I'm asking to understand how much of a priority this task might be

**Comment by valmirtt** [comment]
In our business we support different payment terminals, they are not the majority of our users, but a considerable portion. I understand that even if some of the features are not available, it would be very important for us to support and have the basic SDK working on these terminals.

**Comment by TalbotGooday** [comment]
Got you. I don't promise a quick release, but I will try my best to support your request. Preliminary estimate is the end of the month.

**Comment by TalbotGooday** [comment]
Fixed in 3.4.0
