### ISSUE TITLE
[3.4.0 Version] Fatal Exception: java.lang.NullPointerException in com.helpcrunch.library.repository.storage.in_memory.MemoryRepository.a (SourceFile:9)

### ISSUE THREAD

**Issue by saisasanksunkavalli** [helpcrunch/android-sdk-demo#92]
**SDK Version**: 3.4.0

**Crash Stacktrace**:
 Fatal Exception: java.lang.NullPointerException:
       at com.helpcrunch.library.repository.storage.in_memory.MemoryRepository.a(SourceFile:9)
       at com.helpcrunch.library.repository.use_cases.HcGetAgentUseCase.a(SourceFile:1)
       at com.helpcrunch.library.ui.screens.chat.HcChatViewModel.a(SourceFile:86)
       at com.helpcrunch.library.ui.screens.chat.bot_warden.BotWarden$special$$inlined$map$1$2.emit(SourceFile:172)
       at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
       at com.helpcrunch.library.ui.screens.chat.bot_warden.BotWarden$special$$inlined$map$1.collect(SourceFile:1)
       at kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1.invokeSuspend(Share.kt:210)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.DispatchedContinuation.resumeUndispatchedWith$kotlinx_coroutines_core(DispatchedContinuation.java:252)
       at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:278)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
       at kotlinx.coroutines.BuildersKt.launch(Builders.kt:1)
       at kotlinx.coroutines.flow.FlowKt__ShareKt.launchSharing$FlowKt__ShareKt(Share.kt:205)
       at kotlinx.coroutines.flow.FlowKt__ShareKt.stateIn(Share.kt:310)
       at kotlinx.coroutines.flow.FlowKt.stateIn(Flow.kt:1)
       at com.helpcrunch.library.ui.screens.chat.bot_warden.BotWarden.<init>(SourceFile:635)
       at com.helpcrunch.library.ui.screens.chat.HcChatFragment.S(SourceFile:7)
       at com.helpcrunch.library.ui.screens.chat.HcChatFragment.onViewCreated(SourceFile:3)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:496)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:311)
       at com.helpcrunch.library.ui.screens.main.HelpCrunchMainActivity.onResume(SourceFile:1)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1477)
       at android.app.Activity.performResume(Activity.java:8190)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4748)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4791)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7880)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
        
  `Happening on all Android OS versions: 10, 11, 12, 13 & 14. `

**Comment by saisasanksunkavalli** [comment]
@TalbotGooday  Any update on the above-reported issue? Users in production are still facing the problem/crash.

**Comment by TalbotGooday** [comment]
@saisasanksunkavalli  Potentially, the problem was in the proguard settings. We fixed these problems in the latest version 3.4.1, so I recommend updating
